### PR TITLE
Fixing plugins

### PR DESCRIPTION
**Pull request by Rider21**
Fixed broken plugins: LightNovelReader (English), Agitoon (Korean), Author.today (Russian), Bookriver (Russian), RanobeLib (Russian), RanobeHub (Russian), RanobeRF (Russian), Renovels (Russian), 
Added display of plugin icons in web version

### CODE REVIEW

**Comment by Rider21** [comment]
Added all filters for multisrc readwn, rulate

**Comment by nyagami** [comment]
Why noveltl sources were removed

**Comment by Rider21** [comment]
I combined all these multisources into one plugin. 
And it seems to work (no complaints, on github, discord)

**Comment by nyagami** [comment]
cool

**Review by rajarshee-harness — APPROVED** [review]

**Pull request merged**
